import urllib

from service.image_processing_service import ProcessingImage
import urllib.request


class ProcessingServiceTest:

    @staticmethod
    def process_images_for_retraining():
        THUMB_URL = "http://localhost:8000/"
        THUMB_PREFIX = "photo-thumb/"
        image_id = 13
        url = f"{THUMB_URL}{THUMB_PREFIX}{image_id}"
        with urllib.request.urlopen(url) as url_response:
            img_data = url_response.read()

        return [
            ProcessingImage(2, 13, img_data, verdict_scene=1),
            ProcessingImage(3, 13, img_data, verdict_scene=1),
            ProcessingImage(4, 13, img_data, verdict_scene=1),
            ProcessingImage(5, 13, img_data, verdict_scene=1),
            ProcessingImage(6, 13, img_data, verdict_scene=1),
            ProcessingImage(7, 13, img_data, verdict_scene=1),
            ProcessingImage(8, 13, img_data, verdict_scene=1),
            ProcessingImage(9, 13, img_data, verdict_scene=1),
            ProcessingImage(10, 13, img_data, verdict_scene=1),
            ProcessingImage(11, 13, img_data, verdict_scene=1),
            ProcessingImage(12, 13, img_data, verdict_scene=1),
            ProcessingImage(13, 13, img_data, verdict_scene=1),
            ProcessingImage(14, 13, img_data, verdict_scene=1),
            ProcessingImage(15, 13, img_data, verdict_scene=1),
            ProcessingImage(16, 13, img_data, verdict_scene=1),
            ProcessingImage(17, 13, img_data, verdict_scene=1),
            ProcessingImage(18, 13, img_data, verdict_scene=1),
            ProcessingImage(19, 13, img_data, verdict_scene=1),
            ProcessingImage(20, 13, img_data, verdict_scene=1),
            ProcessingImage(21, 13, img_data, verdict_scene=1),
            ProcessingImage(22, 13, img_data, verdict_scene=1),
            ProcessingImage(23, 13, img_data, verdict_scene=1),
            ProcessingImage(24, 13, img_data, verdict_scene=1),
            ProcessingImage(25, 13, img_data, verdict_scene=1),
            ProcessingImage(26, 13, img_data, verdict_scene=1),
            ProcessingImage(27, 13, img_data, verdict_scene=1),
            ProcessingImage(28, 13, img_data, verdict_scene=1),
            ProcessingImage(29, 13, img_data, verdict_scene=1),
            ProcessingImage(30, 13, img_data, verdict_scene=1),
            ProcessingImage(31, 13, img_data, verdict_scene=1),
            ProcessingImage(32, 13, img_data, verdict_scene=1),
            ProcessingImage(33, 13, img_data, verdict_scene=1),
            ProcessingImage(34, 13, img_data, verdict_scene=1),
            ProcessingImage(35, 13, img_data, verdict_scene=1),
            ProcessingImage(36, 13, img_data, verdict_scene=1),
            ProcessingImage(37, 13, img_data, verdict_scene=1),
            ProcessingImage(38, 13, img_data, verdict_scene=1),
            ProcessingImage(39, 13, img_data, verdict_scene=1),
            ProcessingImage(40, 13, img_data, verdict_scene=1),
            ProcessingImage(41, 13, img_data, verdict_scene=1),
            ProcessingImage(42, 13, img_data, verdict_scene=1),
            ProcessingImage(43, 13, img_data, verdict_scene=1),
            ProcessingImage(44, 13, img_data, verdict_scene=1),
            ProcessingImage(45, 13, img_data, verdict_scene=1),
            ProcessingImage(46, 13, img_data, verdict_scene=1),
            ProcessingImage(47, 13, img_data, verdict_scene=1),
            ProcessingImage(48, 13, img_data, verdict_scene=1),
            ProcessingImage(49, 13, img_data, verdict_scene=1),
            ProcessingImage(50, 13, img_data, verdict_scene=1),
            ProcessingImage(51, 13, img_data, verdict_scene=1),
            ProcessingImage(52, 13, img_data, verdict_scene=1),
            ProcessingImage(53, 13, img_data, verdict_scene=1),
            ProcessingImage(54, 13, img_data, verdict_scene=1),
            ProcessingImage(55, 13, img_data, verdict_scene=1),
            ProcessingImage(56, 13, img_data, verdict_scene=1),
            ProcessingImage(57, 13, img_data, verdict_scene=1),
            ProcessingImage(58, 13, img_data, verdict_scene=1),
            ProcessingImage(59, 13, img_data, verdict_scene=1),
            ProcessingImage(60, 13, img_data, verdict_scene=1),
            ProcessingImage(61, 13, img_data, verdict_scene=1),
            ProcessingImage(62, 13, img_data, verdict_scene=1),
            ProcessingImage(63, 13, img_data, verdict_scene=1),
            ProcessingImage(64, 13, img_data, verdict_scene=1),
            ProcessingImage(65, 13, img_data, verdict_scene=1),
            ProcessingImage(66, 13, img_data, verdict_scene=1),
            ProcessingImage(67, 13, img_data, verdict_scene=1),
            ProcessingImage(68, 13, img_data, verdict_scene=1),
            ProcessingImage(69, 13, img_data, verdict_scene=1),
            ProcessingImage(70, 13, img_data, verdict_scene=1),
            ProcessingImage(71, 13, img_data, verdict_scene=1),
            ProcessingImage(72, 13, img_data, verdict_scene=1),
            ProcessingImage(73, 13, img_data, verdict_scene=1),
            ProcessingImage(74, 13, img_data, verdict_scene=1),
            ProcessingImage(75, 13, img_data, verdict_scene=1),
            ProcessingImage(76, 13, img_data, verdict_scene=1),
            ProcessingImage(77, 13, img_data, verdict_scene=1),
            ProcessingImage(78, 13, img_data, verdict_scene=1),
            ProcessingImage(79, 13, img_data, verdict_scene=1),
            ProcessingImage(80, 13, img_data, verdict_scene=1),
            ProcessingImage(81, 13, img_data, verdict_scene=1),
            ProcessingImage(82, 13, img_data, verdict_scene=1),
            ProcessingImage(83, 13, img_data, verdict_scene=1),
            ProcessingImage(84, 13, img_data, verdict_scene=1),
            ProcessingImage(85, 13, img_data, verdict_scene=1),
            ProcessingImage(86, 13, img_data, verdict_scene=1),
            ProcessingImage(87, 13, img_data, verdict_scene=1),
            ProcessingImage(88, 13, img_data, verdict_scene=1),
            ProcessingImage(89, 13, img_data, verdict_scene=1),
            ProcessingImage(90, 13, img_data, verdict_scene=1),
            ProcessingImage(91, 13, img_data, verdict_scene=1),
            ProcessingImage(92, 13, img_data, verdict_scene=1),
            ProcessingImage(93, 13, img_data, verdict_scene=1),
            ProcessingImage(94, 13, img_data, verdict_scene=1),
            ProcessingImage(95, 13, img_data, verdict_scene=1),
            ProcessingImage(96, 13, img_data, verdict_scene=1),
            ProcessingImage(97, 13, img_data, verdict_scene=1),
            ProcessingImage(98, 13, img_data, verdict_scene=1),
            ProcessingImage(99, 13, img_data, verdict_scene=1),
            ProcessingImage(100, 13, img_data, verdict_scene=1)
        ]
